### ISSUE TITLE
panic while reading zip entry stream

### ISSUE THREAD

**Issue by darrell-roberts** [Majored/rs-async-io-utilities#2] opened 2022-04-12 12:47 UTC
Hi,

I am using async_zip to stream zip entry files from a zip archive. It works in most cases but I encountered this today while testing with a zip archive of 14MB in size.

```
thread 'tokio-runtime-worker' panicked at 'range start index 8195 out of range for slice of length 8192', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/async_io_utilities-0.1.2/src/readers/delimiter_reader.rs:80:38
```

I'm using: 

async_zip = "0.0.6"

Here is the backtrace:
```text
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::slice::index::slice_start_index_len_fail
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/slice/index.rs:35:5
   3: <core::ops::range::RangeFrom<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/slice/index.rs:329:13
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/slice/index.rs:15:9
   5: <async_io_utilities::readers::delimiter_reader::AsyncDelimiterReader<R> as tokio::io::async_read::AsyncRead>::poll_read
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/async_io_utilities-0.1.2/src/readers/delimiter_reader.rs:80:38
   6: <tokio::io::util::take::Take<R> as tokio::io::async_read::AsyncRead>::poll_read
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/io/util/take.rs:91:16
   7: <tokio::io::util::buf_reader::BufReader<R> as tokio::io::async_buf_read::AsyncBufRead>::poll_fill_buf
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/io/util/buf_reader.rs:133:20
   8: async_compression::tokio::bufread::generic::decoder::Decoder<R,D>::do_poll_read
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/async-compression-0.3.12/src/tokio/bufread/generic/decoder.rs:71:40
   9: <async_compression::tokio::bufread::generic::decoder::Decoder<R,D> as tokio::io::async_read::AsyncRead>::poll_read
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/async-compression-0.3.12/src/tokio/bufread/generic/decoder.rs:133:15
  10: <async_compression::tokio::bufread::DeflateDecoder<R> as tokio::io::async_read::AsyncRead>::poll_read
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/async-compression-0.3.12/src/tokio/bufread/macros/decoder.rs:69:17
  11: <async_zip::read::CompressionReader<R> as tokio::io::async_read::AsyncRead>::poll_read
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/async_zip-0.0.6/src/read/mod.rs:312:58
  12: <async_zip::read::LocalReader<R> as tokio::io::async_read::AsyncRead>::poll_read
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/async_zip-0.0.6/src/read/mod.rs:134:51
  13: <async_zip::read::ZipEntryReader<R> as tokio::io::async_read::AsyncRead>::poll_read
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/async_zip-0.0.6/src/read/mod.rs:266:20
  14: <tokio::io::util::buf_reader::BufReader<R> as tokio::io::async_buf_read::AsyncBufRead>::poll_fill_buf
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/io/util/buf_reader.rs:133:20
  15: <tokio::io::util::buf_reader::BufReader<R> as tokio::io::async_read::AsyncRead>::poll_read
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/io/util/buf_reader.rs:114:26
  16: tokio_util::util::poll_read_buf
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-util-0.7.1/src/lib.rs:121:20
  17: <tokio_util::io::reader_stream::ReaderStream<R> as futures_core::stream::Stream>::poll_next
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-util-0.7.1/src/io/reader_stream.rs:102:15
  18: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/mod.rs:1626:9
  19: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/next.rs:32:9
  20: zip_stream_panic::stream_zip_entry::{{closure}}
             at ./src/main.rs:17:28
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  22: <async_stream::async_stream::AsyncStream<T,U> as futures_core::stream::Stream>::poll_next
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/async-stream-0.3.3/src/async_stream.rs:53:17
  23: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.21/src/stream.rs:120:9
  24: futures_util::stream::stream::StreamExt::poll_next_unpin
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/mod.rs:1626:9
  25: <futures_util::stream::stream::next::Next<St> as core::future::future::Future>::poll
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.21/src/stream/stream/next.rs:32:9
  26: zip_stream_panic::copy_file::{{closure}}
             at ./src/main.rs:32:44
  27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  28: zip_stream_panic::main::{{closure}}
             at ./src/main.rs:54:36
  29: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
  30: tokio::park::thread::CachedParkThread::block_on::{{closure}}
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:54
  31: tokio::coop::with_budget::{{closure}}
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  32: std::thread::local::LocalKey<T>::try_with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
  33: std::thread::local::LocalKey<T>::with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:389:9
  34: tokio::coop::with_budget
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  35: tokio::coop::budget
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  36: tokio::park::thread::CachedParkThread::block_on
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/park/thread.rs:263:31
  37: tokio::runtime::enter::Enter::block_on
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/enter.rs:151:13
  38: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/thread_pool/mod.rs:73:9
  39: tokio::runtime::Runtime::block_on
             at /home/droberts/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:477:43
  40: zip_stream_panic::main
             at ./src/main.rs:56:3
  41: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by Majored** [comment] 2022-04-12 14:23
Pretty sure this will be a duplicate of https://github.com/Majored/rs-async-io-utilities/issues/1.

Unfortunately haven't had time to fix it yet. Thank you nonetheless.

**Closed by Majored** 2022-04-12 14:23 UTC
